spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.19.240.137:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: dxy123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.blog.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081

